version: '3.8'
services:
  db:
    image: timescale/timescaledb:latest-pg12
    restart: always
    ports:
      - '5107:5432'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - './db:/var/lib/postgresql/data'
